### ISSUE TITLE
Enhance scripts to deploy Knowlg DBs in the AWS environment

### ISSUE THREAD

**Issue by wasup-yash** [Sunbird-Knowlg/knowledge-platform#965]
Enhancing Terraform scripts to deploy Knowlg DBs in the AWS environment
labels: C4GT cohort 2023
---

## Description
I will be adding the terraform scripts which will provision the infra for the aws environment for DBs

## Sub-Goals
- [ ] [adding a script for Neo4j]
- [ ] [adding a script for Cassandra]
- [ ] [adding a script for Redis]

## Expected Outcome
Deployment of the DB over AWS cloud using the Terraform. 

## Implementation Details

Adding the terraform scripts which enable `IAAC`(infrastructure as a code) to support the aws setup with the help of terraform aws provider. Specifically adding helm provision scripts of DBs  

---

### Project
One-click installation of Knowlg in AWS environment.

### Tech Skills Needed:
Kubernetes, Terraform 

### Complexity
Medium

### Time period estimated
5 days

### Category
Feature

### Sub Category
 [Database],[Localization], [Configuration],[Support]

**Comment by Venkateshakula1** [comment]
Ok
