### ISSUE TITLE
 Enhance scripts to deploy Knowlg Services in the AWS environment

### ISSUE THREAD

**Issue by wasup-yash** [Sunbird-Knowlg/knowledge-platform#972]
Enhancing Terraform scripts to deploy Knowlg Services in the AWS environment
labels: C4GT cohort 2023
---

## Description
I will add the terraform scripts to provision the infra for the aws environment for Services.

## Sub-Goals
- [ ] [adding a script for Content]
- [ ] [adding a script for elasticsearch]
- [ ] [adding a script for search(as per azure)]

## Expected Outcome
Deployment of the Services over AWS cloud using Terraform. 

## Implementation Details

Adding the terraform scripts which enable `IAAC`(infrastructure as a code) to support the AWS setup with the help of terraform aws provider. Specifically adding helm provision scripts of Services 

---

### Project
One-click installation of Knowlg in AWS environment.

### Tech Skills Needed:
Kubernetes, Terraform 

### Complexity
Medium

### Time period estimated
5 days

### Category
Feature

**Comment by jayesh9747** [comment]
@wasup-yash  can you share resource related to the sunbird build block assessment service api? or postman ?
